#docker-compose.yml
# This is a sample Docker Compose file for setting up Prometheus, Grafana, Node Exporter, and Process Exporter.
# It includes the necessary configurations and volumes for each service.
# Make sure to adjust the paths and configurations according to your needs.
# Save this file as docker-compose.yml and run `docker-compose up` to start the services.
# You may need to create a prometheus.yml and process-exporter.yml file with the appropriate configurations.
# prometheus.yml

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3131:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    restart: unless-stopped

  process_exporter:
    image: ncabatoff/process-exporter:latest
    volumes:
      - ./process-exporter.yml:/config.yml
      - /proc:/host/proc:ro
    command:
      - "--config.path=/config.yml"
      - "--procfs=/host/proc"
    pid: "host"
    ports:
      - "9256:9256"
    privileged: true
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge